configs:
- id: slack-com
  config:
    template: slack-com.json
    skip: false
  type:
    settings:
      schema: builtin:dt-javascript-runtime.allowed-outbound-connections
      scope: environment
