apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-connection-strings
  labels:
    {{- include "easytrade.labels" . | nindent 4 }}
type: Opaque
stringData:
  SA_PASSWORD: "yourStrong(!)Password"
  JAVA_CONNECTION_STRING: jdbc:sqlserver://{{ .Release.Name }}-db:1433;database=TradeManagement;user=sa;password=$(SA_PASSWORD);encrypt=false;trustServerCertificate=false;loginTimeout=30;
  DOTNET_CONNECTION_STRING: Data Source={{ .Release.Name }}-db;Initial Catalog=TradeManagement;Persist Security Info=True;User ID=sa;Password=$(SA_PASSWORD);TrustServerCertificate=true
  GO_CONNECTION_STRING: sqlserver://sa:$(SA_PASSWORD)@{{ .Release.Name }}-db:1433?database=TradeManagement&connection+encrypt=false&connection+TrustServerCertificate=false&connection+loginTimeout=30
