{{- if .Values.frontendreverseproxy.externalService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontendreverseproxy-ext
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.frontendreverseproxy.externalService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontendreverseproxy.externalService.type }}
  ports:
  {{- if .Values.frontendreverseproxy.externalService.ports }}
    {{- toYaml .Values.frontendreverseproxy.externalService.ports | nindent 4 }}
  {{- else }}
    - port: {{ .Values.frontendreverseproxy.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- end }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
{{- end }}
