apiVersion: v2
name: easytrade
description: A Helm chart for Kubernetes.
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: app
    alias: accountservice
    repository: "file://./charts/app"
    version: "0.1.0"
    condition: accountservice.enabled
  - name: app
    alias: aggregator-service
    repository: "file://./charts/app"
    version: "0.1.0"
    condition: aggregator-service.enabled
  - name: app
    alias: broker-service
    repository: "file://./charts/app"
    version: "0.1.0"
    condition: broker-service.enabled
  - name: app
    alias: calculationservice
    repository: "file://./charts/app"
    version: "0.1.0"
    condition: calculationservice.enabled
  - name: app
    alias: connection-strings
    repository: "file://./charts/app"
    version: "0.1.0"
  - name: app
    alias: contentcreator
    repository: "file://./charts/app"
    version: "0.1.0"
    condition: contentcreator.enabled
  - name: app
    alias: credit-card-order-service
    repository: "file://./charts/app"
    version: "0.1.0"
    condition: credit-card-order-service.enabled
  - name: app
    alias: db
    repository: "file://./charts/app"
    version: "0.1.0"
    condition: db.enabled
  - name: app
    alias: engine
    repository: "file://./charts/app"
    version: "0.1.0"
    condition: engine.enabled
  - name: app
    alias: feature-flag-service-setup
    repository: "file://./charts/app"
    version: "0.1.0"
    condition: feature-flag-service-setup.enabled
  - name: app
    alias: feature-flag-service
    repository: "file://./charts/app"
    version: "0.1.0"
    condition: feature-flag-service.enabled
  - name: app
    alias: frontend
    repository: "file://./charts/app"
    version: "0.1.0"
    condition: frontend.enabled
  - name: app
    alias: frontendreverseproxy
    repository: "file://./charts/app"
    version: "0.1.0"
    condition: frontendreverseproxy.enabled
  - name: app
    alias: kustomization
    repository: "file://./charts/app"
    version: "0.1.0"
    condition: kustomization.enabled
  - name: app
    alias: labels-and-envs
    repository: "file://./charts/app"
    version: "0.1.0"
    condition: labels-and-envs.enabled
  - name: app
    alias: loadgen
    repository: "file://./charts/app"
    version: "0.1.0"
    condition: loadgen.enabled
  - name: app
    alias: loginservice
    repository: "file://./charts/app"
    version: "0.1.0"
    condition: loginservice.enabled
  - name: app
    alias: manager
    repository: "file://./charts/app"
    version: "0.1.0"
    condition: manager.enabled
  - name: app
    alias: offerservice
    repository: "file://./charts/app"
    version: "0.1.0"
    condition: offerservice.enabled
  - name: app
    alias: pricing-service
    repository: "file://./charts/app"
    version: "0.1.0"
    condition: pricing-service.enabled
  - name: app
    alias: problem-operator
    repository: "file://./charts/app"
    version: "0.1.0"
    condition: problem-operator.enabled
  - name: app
    alias: rabbitmq
    repository: "file://./charts/app"
    version: "0.1.0"
    condition: rabbitmq.enabled
  - name: app
    alias: third-party-service
    repository: "file://./charts/app"
    version: "0.1.0"
    condition: third-party-service.enabled
