name: Build easytrade on PR

on:
  pull_request:
    branches:
      - main
  workflow_call:
    secrets:
      SNYK_API_TOKEN:
        required: true

env:
  CONTAINER_REGISTRY: europe-docker.pkg.dev/dynatrace-demoability/docker/easytrade
  HELM_CHART_PATH: helm/easytrade

jobs:
  snyk:
    uses: ./.github/workflows/reusable-snyk.yaml
    permissions:
      security-events: write
      contents: read
      actions: read
    secrets:
      SNYK_API_TOKEN: ${{ secrets.SNYK_API_TOKEN }}

  calc-version:
    uses: ./.github/workflows/reusable-calc-version.yaml

  build-easytrade:
    runs-on: ubuntu-24.04
    needs: calc-version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build easytrade without pushing to docker repository
        uses: ./.github/actions/build-push-images
        with:
          push: false
          tag: ${{ needs.calc-version.outputs.version }}
          registry: ${{ env.CONTAINER_REGISTRY }}

  build-helm-chart:
    runs-on: ubuntu-24.04
    needs: calc-version
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build Helm chart
        uses: ./.github/actions/build-push-helm
        with:
          chart-path: ${{ env.HELM_CHART_PATH }}
          push: false
          version: ${{ needs.calc-version.outputs.version }}
