name: Build and push
on:
  pull_request:
    branches:
      - "main"
    paths:
      - src/**
  push:
    branches:
      - "main"
    paths:
      - src/**
      - ".github/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  GAR_ADDRESS: europe-docker.pkg.dev
  NAMESPACE: easytrade
  REGISTRY: ghcr.io/arctiqdynatracedemo/easytrade
  PACKAGE_BASE: arctiqdynatracedemo/easytrade
  HELM_REGISTRY: oci://ghcr.io/arctiqdynatracedemo/easytrade/helm
  HELM_CHART_PATH: helm/easytrade
  TAG: ${{ github.sha }}

jobs:
  retrieve-images:
    runs-on: ubuntu-24.04
    outputs:
      images: ${{ steps.retrieve-images.outputs.images }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - id: retrieve-images
        run: | 
          IMAGES=$(docker compose -f compose.build.yaml config --services | tr '\n' ',' | sed 's/,$//' | jq -c -R 'split(",")')
          echo "images=$IMAGES"
          echo "images=$IMAGES" >> "$GITHUB_OUTPUT"

  build-push-easytrade:
    runs-on: ubuntu-24.04
    needs: retrieve-images
    strategy:
      matrix:
        image: ${{ fromJSON(needs.retrieve-images.outputs.images) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker images (push event)
        id: build-on-push
        shell: bash
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "Building image ${{ matrix.image }} with tag: $TAG"
          docker build src/${{ matrix.image }} -t ${{ env.REGISTRY }}/${{ matrix.image }}
      - name: Build Docker images (pr event)
        id: build-on-pr
        shell: bash
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "Building image ${{ matrix.image }} with tag: $TAG"
          docker build src/${{ matrix.image }} -t ${{ env.REGISTRY }}/${{ matrix.image }} --annotation "pr_number=${{ github.event.number }}"
      - name: Push Docker images
        shell: bash
        run: |
          echo "Pushing images to registry..."
          docker push ${{ env.REGISTRY }}/${{ matrix.image }}
          echo "Successfully pushed all images with tag: $TAG"

  octopus:
    runs-on: ubuntu-24.04
    needs: [build-push-easytrade, retrieve-images]
    env:
      OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY  }}
      OCTOPUS_URL: ${{ secrets.OCTOPUS_URL }}
      OCTOPUS_SPACE: 'Default'
    steps:
      - name: Create a release in Octopus Deploy üêô
        id: octopus_release 
        uses: OctopusDeploy/create-release-action@v4
        with:
          project: 'easytrade'
          git_ref: ${{ github.head_ref || github.ref }}
          git_commit: ${{ github.event.after || github.event.pull_request.head.sha }}
          package_version: ${{ env.TAG }}